"""
Epub TOC parser for omnibus books.

Supports EPUB2 (toc.ncx) and EPUB3 (nav document).
Handles two NCX structures found in real-world omnibus epubs:
  - Nested: top-level navPoints with child navPoints = child books
  - Flat:   all navPoints at same depth, book titles mixed with chapter entries
"""
import io
import posixpath
import re
import zipfile
from dataclasses import dataclass, field
from typing import Optional
from urllib.parse import unquote

from lxml import etree

# ---------------------------------------------------------------------------
# Patterns used to identify front/back matter and chapter entries
# ---------------------------------------------------------------------------

# Entries to exclude entirely when scanning for child books
_FRONT_BACK_MATTER = re.compile(
    r"^\s*(copyright|title\s*page|cover|contents|table\s*of\s*contents"
    r"|foreword|preface|introduction|acknowledgements?|dedication"
    r"|about\s*the\s*author|also\s*by|newsletter|mailing\s*list"
    r"|free\s*book|free\s*harem|patreon|discord|facebook|twitter"
    r"|instagram|support|connect\s*with|join\s*(the|my)|follow"
    r"|sign\s*up|bonus|excerpt|sample|preview"
    r"|want\s*more|check\s*this\s*out|more\s*from|more\s*stories"
    r"|get\s*(it|them|your)|claim\s*your"
    r"|(final\s+)?status\s*sheet|character\s*sheet|stat\s*sheet"
    r"|links?|resources|connect|social\s*media)\b",
    re.IGNORECASE,
)

# Entries that look like chapter/section entries (not book titles)
_CHAPTER_LIKE = re.compile(
    r"^\s*(chapter|ch\.|prologue|epilogue|interlude|part|section|volume"
    r"|appendix|glossary|afterword|author.s\s*note)\b",
    re.IGNORECASE,
)

# Entries whose title is just a bare number ("1", "2", ...) are chapter entries
# in omnibuses that don't prefix chapters with the word "Chapter".
_BARE_NUMBER = re.compile(r"^\s*\d+\s*$")

# A leading list number, as TOCs often give back matter ("1. Links and More")
# and chapters ("3 - The Return"). Both patterns above are anchored at the
# start of the title, so the number has to come off before they are applied.
_LIST_NUMBER_PREFIX = re.compile(r"^\d+\s*[.):\-–—]\s*|^\d+\s+")

# NCX namespace
_NCX_NS = "http://www.daisy.org/z3986/2005/ncx/"

# EPUB3 nav namespace
_OPS_NS = "http://www.idpf.org/2007/ops"


def _resolve_href(base_dir: str, href: str) -> str:
    """Resolve a manifest/TOC href to a path inside the ZIP.

    Hrefs are URL-encoded (a space is ``%20``, non-ASCII is percent-escaped
    UTF-8) while ZIP entry names are not, so an href has to be unquoted before
    it will match anything in the archive. Any fragment is left attached;
    callers strip it when they want the file path alone.
    """
    if not href:
        return ""
    path, sep, frag = href.partition("#")
    path = unquote(path)
    if base_dir and not path.startswith("/"):
        path = posixpath.normpath(posixpath.join(base_dir, path))
    else:
        path = path.lstrip("/")
    return path + sep + unquote(frag)


class EpubTooLargeError(ValueError):
    """Raised when an epub's contents expand past what we're willing to read."""


@dataclass
class PageIndex:
    """How to turn a NavPoint into a page number, and how many pages there are.

    EPUB2 NCX files generated by Calibre carry ``dtb:totalPageCount`` and reuse
    ``playOrder`` as the page number. EPUB3 has neither: its page numbers live
    in a ``page-list`` nav, keyed by href, so nav entries have to be looked up
    rather than read off the entry itself.
    """

    total_pages: int = 0
    use_play_order: bool = False
    by_href: dict = field(default_factory=dict)   # "file.xhtml#frag" -> page
    by_file: dict = field(default_factory=dict)   # "file.xhtml" -> first page
    # Reported as page_count_method, so it names where the numbers actually
    # came from rather than lumping both sources under one label.
    method: str = ""

    def page_for(self, nav_point) -> Optional[int]:
        """Page this entry starts on, or None if it can't be determined."""
        if self.use_play_order:
            return nav_point.play_order
        page = self.by_href.get(nav_point.full_href)
        if page is None:
            page = self.by_file.get(nav_point.href)
        return page


@dataclass
class NavPoint:
    title: str
    href: str          # path within the ZIP (fragment stripped)
    full_href: str     # original href including fragment
    play_order: int    # doubles as page number in calibre-generated epubs
    children: list = field(default_factory=list)


class EpubParser:
    # A ZIP member's compressed size says nothing about how much it expands to,
    # so the upload limit doesn't bound how much we end up reading. These cap
    # what a single member and a whole epub may decompress to. Only text is
    # ever read (the OPF, the TOC and the spine documents), never images, so
    # even a large illustrated epub stays far below these.
    _MAX_MEMBER_BYTES = 64 * 1024 * 1024
    _MAX_TOTAL_BYTES = 256 * 1024 * 1024

    def __init__(self, file_bytes: bytes):
        self._zip = zipfile.ZipFile(io.BytesIO(file_bytes))
        self._budget = self._MAX_TOTAL_BYTES

    def __enter__(self):
        return self

    def __exit__(self, *exc_info):
        self.close()

    def close(self) -> None:
        self._zip.close()

    def _read(self, path: str) -> bytes:
        """Read a ZIP member, refusing anything that decompresses past a cap."""
        cap = min(self._MAX_MEMBER_BYTES, self._budget)
        with self._zip.open(path) as fh:
            data = fh.read(cap + 1)
        if len(data) > cap:
            raise EpubTooLargeError(
                f"'{path}' expands to more than the {cap} byte limit"
            )
        self._budget -= len(data)
        return data

    def parse(self) -> dict:  # noqa: C901
        opf_path = self._find_opf_path()
        opf_dir = posixpath.dirname(opf_path)

        title, epub_version, toc_path, spine = self._parse_opf(opf_path, opf_dir)

        # ``toc_path`` is already resolved against the OPF directory. If the
        # manifest pointed at something that isn't in the archive, fall back to
        # any toc.ncx we can find.
        names = self._zip.namelist()
        if not toc_path or toc_path not in names:
            candidates = [n for n in names if n.endswith("toc.ncx")]
            toc_path = candidates[0] if candidates else None

        if toc_path is None:
            return {
                "omnibus_title": title,
                "total_pages": 0,
                "page_count_method": "none",
                "child_books": [],
                "toc_entries": [],
                "error": "No TOC file found in epub",
            }

        nav_points, page_index = self._parse_toc(toc_path)

        page_for = self._verified_page_lookup(nav_points, page_index)
        if page_for is not None:
            # The epub carries real page metadata
            page_count_method = page_index.method
            total_pages = page_index.total_pages
            toc_entries = self._build_toc_entries(
                nav_points,
                page_for,
                omnibus_title=title,
                page_cutoff=total_pages,
            )
        else:
            # No page metadata — estimate via word count across the spine
            page_count_method = "word-count-estimate"
            total_pages, toc_entries = self._estimate_pages_from_spine(
                nav_points, title, spine
            )

        # child_books is derived from the same flags that seed the editor's
        # checkboxes, so the table, the JSON and the checkboxes can never
        # disagree about which entries start a book.
        child_books = self._books_from_entries(toc_entries)

        return {
            "omnibus_title": title,
            "total_pages": total_pages,
            "page_count_method": page_count_method,
            "child_books": child_books,
            # Flat list of every TOC entry, each flagged with the parser's
            # best guess at whether it starts a child book. The UI lets the
            # user override these flags when auto-detection gets it wrong.
            "toc_entries": toc_entries,
        }

    # ------------------------------------------------------------------
    # OPF / container parsing
    # ------------------------------------------------------------------

    def _find_opf_path(self) -> str:
        container = self._read("META-INF/container.xml")
        root = etree.fromstring(container)
        # namespace-agnostic search
        for el in root.iter():
            if el.tag.endswith("}rootfile") or el.tag == "rootfile":
                path = el.get("full-path")
                if path:
                    return path
        raise ValueError("Cannot find rootfile in META-INF/container.xml")

    def _parse_opf(self, opf_path: str, opf_dir: str) -> tuple:
        """Returns (title, epub_version, toc_path, spine_paths).

        ``toc_path`` and every spine path are archive paths, resolved against
        ``opf_dir`` and percent-decoded.
        """
        root = etree.fromstring(self._read(opf_path))

        title = self._find_title(root) or "Unknown Title"

        # EPUB version
        epub_version = root.get("version", "2.0")

        # TOC location from manifest/spine
        toc_path = self._find_toc_path(root, epub_version, opf_dir)

        # Build manifest id -> href map, then walk spine itemrefs
        manifest = {}
        for el in root.iter():
            if el.tag.endswith("}item") or el.tag == "item":
                item_id = el.get("id")
                href = el.get("href")
                if item_id and href:
                    manifest[item_id] = _resolve_href(opf_dir, href)

        spine = []
        for el in root.iter():
            if el.tag.endswith("}spine") or el.tag == "spine":
                for itemref in el:
                    idref = itemref.get("idref")
                    if idref and idref in manifest:
                        spine.append(manifest[idref])

        return title, epub_version, toc_path, spine

    @staticmethod
    def _find_title(root) -> str:
        """The omnibus title, preferring the one marked as the main title.

        EPUB3 allows several dc:title elements — subtitle, collection, and so
        on — distinguished by a refining title-type. Taking the first in
        document order picks up a subtitle whenever one happens to be listed
        first.
        """
        dc_title = "{http://purl.org/dc/elements/1.1/}title"
        titles = [el for el in root.iter(dc_title)]
        if not titles:
            return ""

        main_ids = {
            (meta.get("refines") or "").lstrip("#")
            for meta in root.iter()
            if (meta.tag.endswith("}meta") or meta.tag == "meta")
            and meta.get("property") == "title-type"
            and (meta.text or "").strip() == "main"
        }
        for el in titles:
            if el.get("id") and el.get("id") in main_ids:
                return (el.text or "").strip()
        return (titles[0].text or "").strip()

    def _find_toc_path(self, root, epub_version: str, opf_dir: str) -> Optional[str]:
        """Archive path of the nav document (EPUB3) or toc.ncx (EPUB2).

        Manifest hrefs are relative to the OPF directory; the zip-scan fallback
        already yields a full archive path. Everything is returned resolved so
        callers never have to know which branch produced it.
        """
        if epub_version.startswith("3"):
            # EPUB3: look for <item properties="nav"> in manifest
            for el in root.iter():
                if el.tag.endswith("}item") or el.tag == "item":
                    props = el.get("properties", "")
                    if "nav" in props.split() and el.get("href"):
                        return _resolve_href(opf_dir, el.get("href"))

        # EPUB2: look for toc attribute on <spine>
        for el in root.iter():
            if el.tag.endswith("}spine") or el.tag == "spine":
                toc_id = el.get("toc")
                if toc_id:
                    # Find item with this id in manifest
                    for item in root.iter():
                        if (item.tag.endswith("}item") or item.tag == "item"):
                            if item.get("id") == toc_id and item.get("href"):
                                return _resolve_href(opf_dir, item.get("href"))

        # Fallback: find toc.ncx in zip
        for name in self._zip.namelist():
            if name.endswith("toc.ncx"):
                return name
        return None

    # ------------------------------------------------------------------
    # TOC parsing
    # ------------------------------------------------------------------

    def _parse_toc(self, toc_path: str) -> tuple:
        """Parse the TOC, dispatching on what the file actually is.

        The package's ``version`` attribute isn't a reliable guide: EPUB3
        packages normally ship a toc.ncx alongside the nav document for
        backwards compatibility, and some declare version 3 while providing
        only the NCX. Sniffing the root element picks the right parser for the
        file we actually ended up with.
        """
        root = etree.fromstring(self._read(toc_path))
        toc_dir = posixpath.dirname(toc_path)
        tag = root.tag.split("}")[-1] if "}" in root.tag else root.tag
        if tag == "ncx":
            return self._parse_ncx(root, toc_dir)
        return self._parse_nav(root, toc_dir)

    @staticmethod
    def _iter_nav_points(nav_points: list):
        """Every NavPoint in the tree, parents before children."""
        for np in nav_points:
            yield np
            yield from EpubParser._iter_nav_points(np.children)

    def _verified_page_lookup(self, nav_points: list, page_index: PageIndex):
        """``page_index.page_for`` if it covers every entry, else None.

        A page-list that doesn't line up with the TOC would otherwise yield
        page numbers for some entries and nothing for the rest; a word-count
        estimate for all of them beats a mixture of the two.
        """
        if page_index.total_pages <= 0:
            return None
        if any(
            page_index.page_for(np) is None
            for np in self._iter_nav_points(nav_points)
        ):
            return None
        return page_index.page_for

    # ------------------------------------------------------------------
    # EPUB2 NCX parsing
    # ------------------------------------------------------------------

    def _parse_ncx(self, root, ncx_dir: str) -> tuple:
        """Returns (list[NavPoint], PageIndex)."""

        def ncx(tag):
            return f"{{{_NCX_NS}}}{tag}"

        # Total pages from metadata
        total_pages = 0
        for meta in root.iter(ncx("meta")):
            name = meta.get("name", "")
            if name in ("dtb:totalPageCount", "dtb:maxPageNumber"):
                val = meta.get("content", "0")
                try:
                    n = int(val)
                    if n > total_pages:
                        total_pages = n
                except ValueError:
                    pass

        # In a Calibre-generated NCX, playOrder doubles as the page number.
        page_index = PageIndex(
            total_pages=total_pages,
            use_play_order=True,
            method="ncx-metadata",
        )

        # Parse navMap
        nav_map = root.find(ncx("navMap"))
        if nav_map is None:
            return [], page_index

        def parse_nav_point(el) -> NavPoint:
            title_el = el.find(f"{ncx('navLabel')}/{ncx('text')}")
            title = (title_el.text or "").strip() if title_el is not None else ""

            content_el = el.find(ncx("content"))
            raw_href = content_el.get("src", "") if content_el is not None else ""

            resolved = _resolve_href(ncx_dir, raw_href)

            # Strip fragment for ZIP lookup
            href_no_frag = resolved.split("#")[0]

            try:
                play_order = int(el.get("playOrder", "0"))
            except ValueError:
                play_order = 0

            children = [
                parse_nav_point(child)
                for child in el.iterchildren(ncx("navPoint"))
            ]

            return NavPoint(
                title=title,
                href=href_no_frag,
                full_href=resolved,
                play_order=play_order,
                children=children,
            )

        nav_points = [
            parse_nav_point(el)
            for el in nav_map.iterchildren(ncx("navPoint"))
        ]

        return nav_points, page_index

    # ------------------------------------------------------------------
    # EPUB3 nav parsing
    # ------------------------------------------------------------------

    def _parse_nav(self, root, nav_dir: str) -> tuple:
        """Returns (list[NavPoint], PageIndex)."""

        def ops_type(el):
            # Check both namespaced and prefixed forms
            t = el.get(f"{{{_OPS_NS}}}type") or el.get("epub:type") or ""
            return t

        toc_nav = None
        for el in root.iter():
            if el.tag.endswith("}nav") or el.tag == "nav":
                if "toc" in ops_type(el):
                    toc_nav = el
                    break

        if toc_nav is None:
            return [], PageIndex()

        def href_to_path(href: str) -> str:
            return _resolve_href(nav_dir, href)

        def parse_li(li_el, play_order_counter: list) -> NavPoint:
            # Number this entry before descending, so an entry always comes
            # before everything nested under it.
            play_order_counter[0] += 1
            play_order = play_order_counter[0]

            title = ""
            href = ""
            full_href = ""
            children = []

            for child in li_el:
                local = child.tag.split("}")[-1] if "}" in child.tag else child.tag
                if local == "a":
                    # Extract text content (may include nested spans)
                    title = "".join(child.itertext()).strip()
                    raw_href = child.get("href", "")
                    full_href = href_to_path(raw_href)
                    href = full_href.split("#")[0]
                elif local == "span":
                    title = "".join(child.itertext()).strip()
                elif local == "ol":
                    for sub_li in child:
                        sub_local = sub_li.tag.split("}")[-1] if "}" in sub_li.tag else sub_li.tag
                        if sub_local == "li":
                            children.append(parse_li(sub_li, play_order_counter))

            return NavPoint(
                title=title,
                href=href,
                full_href=full_href,
                play_order=play_order,
                children=children,
            )

        nav_points = []
        counter = [0]
        top_ol = toc_nav.find(".//{*}ol")
        if top_ol is not None:
            for li in top_ol:
                local = li.tag.split("}")[-1] if "}" in li.tag else li.tag
                if local == "li":
                    nav_points.append(parse_li(li, counter))

        # EPUB3 has no dtb:totalPageCount; page numbers come from page-list.
        return nav_points, self._parse_page_list(root, nav_dir)

    def _parse_page_list(self, root, nav_dir: str) -> PageIndex:
        """Build a href -> page number index from the EPUB3 page-list nav.

        Unlike NCX playOrder, an EPUB3 nav entry carries no page number of its
        own, so pages have to be read from the page-list and matched back to
        TOC hrefs. Page labels are used when they are all plain numbers (they
        may be roman numerals for front matter); otherwise entries are numbered
        by position.
        """
        page_list = None
        for el in root.iter():
            if el.tag.endswith("}nav") or el.tag == "nav":
                t = el.get(f"{{{_OPS_NS}}}type") or el.get("epub:type") or ""
                if "page-list" in t:
                    page_list = el
                    break

        if page_list is None:
            return PageIndex()

        targets = []   # (full_href, label)
        for a in page_list.iter():
            local = a.tag.split("}")[-1] if "}" in a.tag else a.tag
            if local != "a":
                continue
            href = a.get("href")
            if href:
                targets.append((
                    _resolve_href(nav_dir, href),
                    "".join(a.itertext()).strip(),
                ))

        if not targets:
            return PageIndex()

        labels = [label for _, label in targets]
        if all(_BARE_NUMBER.match(label) for label in labels):
            # The page-list's own labels are the printed page numbers.
            numbers = [int(label) for label in labels]
            method = "page-list-metadata"
        else:
            # Labels the epub doesn't number plainly (roman-numeral front
            # matter, "Page 12", ...). The page breaks are still real, so
            # entries are counted by position, but the resulting numbers are
            # page ordinals rather than the edition's printed labels.
            numbers = list(range(1, len(targets) + 1))
            method = "page-list-ordinal"

        index = PageIndex(total_pages=max(numbers), method=method)
        for (full_href, _), page in zip(targets, numbers):
            index.by_href.setdefault(full_href, page)
            index.by_file.setdefault(full_href.split("#")[0], page)
        return index

    # ------------------------------------------------------------------
    # Child book detection
    # ------------------------------------------------------------------

    @classmethod
    def _is_book_candidate(cls, title: str) -> bool:
        """True if a flat-TOC entry title could be a child-book boundary.

        Excludes blank titles, front/back matter, chapter-like headings, and
        bare-number chapter entries ("1", "2", ...).
        """
        t = title.strip()
        if not t:
            return False
        if _BARE_NUMBER.match(t):
            return False

        # "1. Links and More" is the back matter "Links and More", and
        # "2 - Chapter Two" is a chapter; test the title without its list
        # number so the leading digits don't shield it from the patterns.
        unnumbered = _LIST_NUMBER_PREFIX.sub("", t) or t
        if _FRONT_BACK_MATTER.match(unnumbered):
            return False
        if _CHAPTER_LIKE.match(unnumbered):
            return False
        return True

    def _build_toc_entries(
        self,
        nav_points: list,
        start_page_for,
        omnibus_title: str = "",
        page_cutoff: int = 0,
    ) -> list:
        """Flatten nav_points into a list of entry dicts.

        Each entry is ``{title, start_page, is_book_start}``, plus an optional
        ``book_title`` when the name of the book that starts here differs from
        the TOC label (see the inferred book 1 below).

        ``start_page_for`` maps a NavPoint to its start page (playOrder for
        page-metadata epubs, or a word-count estimate otherwise).

        ``page_cutoff`` (when > 0) suppresses book-start flags for entries that
        start beyond the real page count — these are back-matter promos rather
        than child books.

        ``is_book_start`` is the parser's best guess: it seeds the checkboxes
        in the manual book-start editor, and ``child_books`` is derived from it,
        so the two always agree. The user can override any of them.
        """
        nested = any(np.children for np in nav_points)
        entries = []

        if nested:
            # Nested structure: top-level navPoints that HAVE children are the
            # child books; everything below them is a chapter.
            def walk(np, is_top):
                entries.append({
                    "title": np.title,
                    "start_page": start_page_for(np),
                    "is_book_start": bool(is_top and np.children),
                })
                for child in np.children:
                    walk(child, False)

            for np in nav_points:
                walk(np, True)
            return entries

        # Flat structure: every entry sits at the same depth, so book titles
        # have to be told apart from chapter entries by name.
        for np in nav_points:
            entries.append({
                "title": np.title,
                "start_page": start_page_for(np),
                "is_book_start": False,
            })

        candidates = [
            i for i, np in enumerate(nav_points)
            if self._is_book_candidate(np.title)
            and not (page_cutoff and entries[i]["start_page"] > page_cutoff)
        ]
        if not candidates:
            return entries

        # A lone candidate with no number in it is probably the omnibus's own
        # title page rather than a child book — we can't split on that.
        if len(candidates) == 1 and not re.search(r"\d", nav_points[candidates[0]].title):
            return entries

        for i in candidates:
            entries[i]["is_book_start"] = True

        # If a "Chapter 1"/"Prologue" entry comes before the first candidate,
        # book 1 has no title entry of its own: its first chapter is where it
        # starts, and its name has to be derived from its siblings.
        first_chapter = next(
            (
                i for i, np in enumerate(nav_points)
                if re.match(r"^\s*(chapter\s*(1|one)|prologue)\b", np.title, re.IGNORECASE)
            ),
            None,
        )
        if first_chapter is not None and first_chapter < candidates[0]:
            entries[first_chapter]["is_book_start"] = True
            entries[first_chapter]["book_title"] = self._infer_book1_title_from_siblings(
                [nav_points[i].title for i in candidates], omnibus_title
            )

        return entries

    @staticmethod
    def _books_from_entries(entries: list) -> list:
        """Build the child_books list from the entries flagged as book starts."""
        books = [
            {
                "title": entry.get("book_title") or entry["title"],
                "start_page": entry["start_page"],
            }
            for entry in entries
            if entry["is_book_start"]
        ]
        return EpubParser._number_duplicate_titles(books)

    @staticmethod
    def _number_duplicate_titles(books: list) -> list:
        """When multiple child books share the same title, append Book N suffixes."""
        from collections import Counter
        counts = Counter(b["title"] for b in books)
        duplicates = {t for t, n in counts.items() if n > 1}
        if not duplicates:
            return books
        indices = {t: 0 for t in duplicates}
        result = []
        for book in books:
            if book["title"] in duplicates:
                indices[book["title"]] += 1
                result.append({
                    "title": f"{book['title']} {indices[book['title']]}",
                    "start_page": book["start_page"],
                })
            else:
                result.append(book)
        return result

    @staticmethod
    def _infer_book1_title_from_siblings(
        sibling_titles: list, omnibus_title: str
    ) -> str:
        """
        Derive Book 1 title from the sibling book entries.

        Strategy: find the longest common prefix shared by all sibling titles
        (e.g. "Battle Mage 2", "Battle Mage 3" -> prefix "Battle Mage").
        Falls back to stripping qualifier words from the omnibus title.
        """
        if sibling_titles:
            # Strip trailing numbers/words from each sibling to find base name
            bases = []
            for t in sibling_titles:
                base = re.sub(r"\s+\d+\s*$", "", t).strip()
                if base and base != t:
                    bases.append(base)
            if bases and len(set(bases)) == 1:
                return bases[0]

            # Fallback: common prefix of all sibling titles (word-level)
            words_list = [t.split() for t in sibling_titles]
            if words_list:
                prefix_words = words_list[0]
                for words in words_list[1:]:
                    prefix_words = [
                        w for w, v in zip(prefix_words, words) if w == v
                    ]
                if prefix_words:
                    return " ".join(prefix_words)

        # Last resort: strip omnibus qualifier from the omnibus title
        cleaned = re.sub(
            r"\s*[:\-–—]\s*(omnibus|books?\s*\d|complete\s*series|the\s*complete).*$",
            "",
            omnibus_title,
            flags=re.IGNORECASE,
        ).strip()
        cleaned = re.sub(
            r"\s*\((books?\s*\d.*|omnibus.*|complete.*)\)\s*$",
            "",
            cleaned,
            flags=re.IGNORECASE,
        ).strip()
        return cleaned if cleaned else "Book 1"

    # ------------------------------------------------------------------
    # Word count fallback (epubs with no page metadata)
    # ------------------------------------------------------------------

    _TAG_RE = re.compile(r"<[^>]+>")
    _WORDS_PER_PAGE = 250

    def _estimate_pages_from_spine(
        self, nav_points: list, omnibus_title: str, spine: list
    ) -> tuple:
        """
        Estimate total pages and TOC entry start pages via word count.

        Returns (total_pages, toc_entries).
        """
        zip_names = set(self._zip.namelist())

        # Word count per spine file (in order)
        spine_word_counts = []
        for path in spine:
            if path in zip_names:
                try:
                    raw = self._read(path).decode("utf-8", errors="replace")
                    text = self._TAG_RE.sub(" ", raw)
                    spine_word_counts.append((path, len(text.split())))
                except EpubTooLargeError:
                    raise
                except Exception:
                    spine_word_counts.append((path, 0))

        total_words = sum(wc for _, wc in spine_word_counts)
        total_pages = max(1, round(total_words / self._WORDS_PER_PAGE))

        # Build a lookup: spine file path -> cumulative word count before that file
        cumulative = 0
        words_before = {}
        for path, wc in spine_word_counts:
            words_before.setdefault(path, cumulative)
            cumulative += wc

        def words_to_page(words: int) -> int:
            # Clamped to total_pages: rounding can otherwise put a short
            # trailing entry one page past the end of the book.
            return min(total_pages, max(1, round(words / self._WORDS_PER_PAGE) + 1))

        def find_words_before(href: str) -> int:
            # Try exact match first, then basename match
            if href in words_before:
                return words_before[href]
            base = posixpath.basename(href)
            for path, wc in words_before.items():
                if posixpath.basename(path) == base:
                    return wc
            return 0

        toc_entries = self._build_toc_entries(
            nav_points,
            lambda np: words_to_page(find_words_before(np.href)),
            omnibus_title=omnibus_title,
            page_cutoff=total_pages,
        )

        return total_pages, toc_entries
